### ISSUE TITLE
Add support for APACK

### ISSUE THREAD

**Issue by andkopp** [ABAP-Logger/ABAP-Logger#42]
See details here: https://blogs.sap.com/2019/05/06/introducing-apack-a-package-and-dependency-manager-for-abap/

The ABAP Environment on SAP Cloud Platform will support a Maven like dependency management and therefore a new interface needs to be implemented.

**Comment by epeterson320** [comment]
Just read the article. Looks really exciting. Would love to get this integrated!

**Comment by DerGuteWolf** [comment]
Currently this is rather pointless, since all functions modules BAL_LOG_* are not available in ABAP Environment on SAP Cloud Platform...

**Comment by andkopp** [comment]
I guess that most of the features that come to the cloud version of ABAP first will also come to the on-premise version. One example is the Restful ABAP Programming Model which will be released with 1809 to on-premise.

If not, a new ZCL_LOGGER_CLOUD implementation would be required. And there is another problem in the cloud: as far as I know RTTI (Runtime Type Services) is not fully available yet - only https://github.com/SAP/abap-platform-yy.

**Comment by DerGuteWolf** [comment]
> I guess that most of the features that come to the cloud version of ABAP first will also come to the on-premise version. One example is the Restful ABAP Programming Model which will be released with 1809 to on-premise.

But only to 1809. There are lot's of SAP customers who are on some version below 1809 or on ERP EHP8,7,6 ....

But the problem here is that ABAP Cloud made lot's of stuff inaccessible, eg everything regarding logging.

> If not, a new ZCL_LOGGER_CLOUD implementation would be required. And there is another problem in the cloud: as far as I know RTTI (Runtime Type Services) is not fully available yet - only https://github.com/SAP/abap-platform-yy.

Yes, but according to the roadmap we might get RTTI for ABAP Cloud in release v1911....

IMHO this all takes too long. Without stuff like RTTI, logging, JSON parsing, i18n, etc.  steampunk is almost unusable for anything serious
