### ISSUE TITLE
Failing Unit Test with different Text Values [Language Problem]

### ISSUE THREAD

**Issue by HuprichTo** [ABAP-Logger/ABAP-Logger#92]
Hello, 

via the automated Test run in our System, the following Methods of LCL_TEST of ZCL_LOGGER fail: 
- can_log_batch_msgs
- can_og_chained_exceptions

It's obviously that some kind of language conflict exists here, the system language is German (D), but the Logger Class is executing the Tests in English. By changing the sy-langu to German during Debugger Session, the Tests will pass.

Below are the Error Messages:
![image](https://user-images.githubusercontent.com/73161936/133752193-18e3e8a4-e147-45e4-948c-f4a8adce5da4.png)
![image](https://user-images.githubusercontent.com/73161936/133752205-a7472525-5dad-4a9b-87d9-fff7e2e1683a.png)

Code where the false Text Components are set: 
![image](https://user-images.githubusercontent.com/73161936/133752386-5873a145-ae58-40fa-b0d7-89b088e6c91c.png)

By switching Logon Language to English, tests also pass but it would be nice to stay in German Environnement for that.

My question is now what do I have to do to resolve this issue? On the first try I didn't found the Text Elements to translate them...

**Comment by pokrakam** [comment]
The problem is actually in the BAL message reader. ABAP Unit tests run in the text environment language of the original language of the object being tested, so SY-LANGU is set to 'E' by the unit test framework. But when generating the texts it uses `MESSAGE ... INTO` which will always log in the original logon language. You can see this by debugging here:
<img width="458" alt="image" src="https://user-images.githubusercontent.com/25539927/133923883-98f50e23-a180-449c-b818-7e857d0ed274.png">
both languages are 'E' when logged on in German.
https://help.sap.com/doc/abapdocu_755_index_htm/7.55/en-US/index.htm?file=abenlanguage_settings.htm

It is theoretically possible to override this using SET LOCALE LANGUAGE at the start of the unit test. You can add these two lines at the beginning of class_setup to pass tests in German:
<img width="622" alt="image" src="https://user-images.githubusercontent.com/25539927/133924130-8d1da62f-4a42-4433-ab51-6abef04baab9.png">
But I would not recommend this as a solution because it may cause issues on systems with other logon languages and additional complexity of languages that may or may not be installed. Tests should rather be isolated from any language dependency.
